---
volumes:
  mylearn:
    driver: local
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8077:80"
    environment:
        - PMA_HOST=db
    restart: always
    depends_on:
        - db
    
  db:
    image: mysql:8.0
    container_name: learn_mysql
    volumes:
      - mylearn:/var/lib/mysql
    ports:
      - "5506:3306"
    restart: always
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD
        - MYSQL_PASSWORD={{PW}}  # change!
        - MYSQL_ROOT_PASSWORD={{PW}}  # change!
        - MYSQL_DATABASE=learn_mysql
         
  
