events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        # Umleitung aller HTTP-Anfragen auf HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /ssl/rep.crt;
		ssl_certificate_key /ssl/rep.key;

		
		location / {
			proxy_pass http://192.168.0.78:8200/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header X-Forwarded-Host $host;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_buffers 16 4k;
			proxy_buffer_size 2k;

			# sub_filter um absolute Pfade in relative umzuwandeln
			sub_filter 'http://192.168.0.78:8200/' '/';
			sub_filter_once off;
		}


        location /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
        }

        location /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
        }
	
	

    }
}

