version: "3.3"

services:
  #webserver
  apache:
    image: webdevops/apache:latest
    container_name: "${IMAGE_NAME_APACHE}"
    environment:
      - WEB_PHP_SOCKET=php:9000
    volumes:
      - /home/torsten/php/src:/app
    ports:
      - 80:80
    
  #php
  php:
    build: ./php
    container_name: "${IMAGE_NAME_PHP}"
    extra_hosts:
      - host.docker.internal:host-gateway
    #environment:
      #XDEBUG_MODE: debug
      #XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - /home/torsten/php/src:/app

  # Database
  db:
   platform: linux/x86_64
   image: mysql:5.7
   container_name: "mysql"
   volumes:
     - db_data:/var/lib/mysql
   restart: always
   ports:
      - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: devdb
     MYSQL_PASSWORD: password
     MYSQL_USER: devuser


   #myadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8077:80"
    environment:
        - PMA_HOST=db
    restart: always
    depends_on:
        - db


volumes:
  db_data:
    name: ${VOL_NAME}
